# Generated by Django 4.0.5 on 2022-06-27 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('original_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('promotion_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('promotion_percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('additional_information', models.TextField()),
                ('promotion', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('longeur', models.CharField(blank=True, max_length=50)),
                ('largeur', models.CharField(blank=True, max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='product_categories', to='front.categories'),
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='front.products'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.products'),
        ),
        migrations.AlterField(
            model_name='dealoftheweenk',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DealOfTheWeenk_product', to='front.products'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_product_product', to='front.products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product', to='front.products'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
