# Generated by Django 4.0.5 on 2022-07-05 12:57

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_comments_products_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='promotion',
            new_name='is_promotion',
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default='Exemple', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='Popo.img', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='original_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion_percentage',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('code_hex', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protruct_color', to='front.products')),
            ],
        ),
    ]
