# Generated by Django 4.0.5 on 2022-07-02 14:11

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_comments_products_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='photo',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_image',
            field=models.ImageField(default='fgyfyfuyf', upload_to='product_cats'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('color_code', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protruct_color', to='front.products')),
            ],
        ),
    ]
