# Generated by Django 4.0.5 on 2022-07-02 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_rename_photo_products_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='promotion',
            new_name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='products',
            name='promotion_price',
        ),
        migrations.AddField(
            model_name='products',
            name='is_solde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='promotion_reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='original_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
