# Generated by Django 4.0.5 on 2022-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_rename_promotion_products_is_promotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
