# Generated by Django 4.0.5 on 2022-07-15 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_cart_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='promotion_price',
        ),
        migrations.AddField(
            model_name='products',
            name='promotion_reduction',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
