# Generated by Django 4.0.5 on 2022-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_cart_alter_products_options_imageproduct_photo_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='photo_desc',
            new_name='photo_desc_1',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='photo_desc_2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='photo_desc_3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
