# Generated by Django 4.0.5 on 2022-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_rename_photo_desc_imageproduct_photo_desc_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='photo',
            field=models.ImageField(upload_to='img_product'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='photo_desc_1',
            field=models.ImageField(blank=True, upload_to='img_product_desc1'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='photo_desc_2',
            field=models.ImageField(blank=True, upload_to='img_product_desc2'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='photo_desc_3',
            field=models.ImageField(blank=True, upload_to='img_product_desc2'),
        ),
    ]
