# Generated by Django 4.0.5 on 2022-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_alter_imageproduct_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
