# Generated by Django 4.0.5 on 2022-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_alter_products_promotion_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
