# Generated by Django 4.0.5 on 2022-07-16 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0009_order_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_cart',
            new_name='is_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oder_cart', to='front.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Card_products', to='front.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
