# Generated by Django 4.0.5 on 2022-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_products_stock'),
        ('front', '0009_alter_products_active'),
    ]

    operations = [
    ]
