# Generated by Django 4.0.5 on 2022-07-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_size_alter_orderitem_quantity_remove_products_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
