# Generated by Django 4.0.5 on 2022-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_cart_quantity_cart_session_id_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.products'),
            preserve_default=False,
        ),
    ]
