# Generated by Django 4.0.5 on 2022-07-24 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_city_deliveryaddress_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.city'),
            preserve_default=False,
        ),
    ]
