# Generated by Django 4.0.5 on 2022-07-25 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0019_deliveryaddress_city_deliveryaddress_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='last_name',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address_district', to='front.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
