# Generated by Django 4.0.5 on 2022-07-25 02:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_remove_deliveryaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0105020608', max_length=128, region='CI'),
            preserve_default=False,
        ),
    ]
