# Generated by Django 4.0.5 on 2022-07-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0022_deliverymethod_payment_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confimation', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.cart')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.deliveryaddress')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.deliverymethod')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
