# Generated by Django 4.0.5 on 2022-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0025_alter_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
