# Generated by Django 4.0.5 on 2022-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0027_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='products',
            name='longeur',
        ),
        migrations.AddField(
            model_name='promotion',
            name='mini_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
