# Generated by Django 4.0.5 on 2022-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0028_remove_products_largeur_remove_products_longeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
