# Generated by Django 4.0.5 on 2022-08-02 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0030_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheweenk',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealoftheweenk',
            name='end_of_deal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dealoftheweenk',
            name='start_of_deal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
