# Generated by Django 4.0.5 on 2022-07-05 12:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CI', unique=True),
        ),
    ]
