# Generated by Django 4.0.5 on 2022-07-21 16:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CI'),
        ),
    ]
