# Generated by Django 4.0.5 on 2022-07-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_deliveryaddress_city_deliveryaddress_created_and_more'),
        ('authentication', '0004_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.deliveryaddress'),
        ),
    ]
