# Generated by Django 4.0.5 on 2022-07-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_deliveryaddress_city_deliveryaddress_created_and_more'),
        ('authentication', '0005_user_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, null=True, to='front.deliveryaddress'),
        ),
    ]
