# Generated by Django 4.0.5 on 2022-07-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_remove_deliveryaddress_city_and_more'),
        ('authentication', '0006_remove_user_delivery_address_user_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_delivery_address', to='front.deliveryaddress'),
        ),
    ]
